services:
  db:
    image: 'postgres:latest'
    container_name: db_chilibeans
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app_chilibeans
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}